// Curated NFT mint data — dates relative to May 2026
export const MINTS = [
  {
    id: 'neon-genesis',
    name: 'Neon Genesis',
    image: 'https://picsum.photos/seed/neongenesis/400/400',
    banner: 'https://picsum.photos/seed/neongenesisBanner/800/300',
    chain: 'ethereum',
    price: '0.08',
    currency: 'ETH',
    supply: 8888,
    mintDate: '2026-05-22T18:00:00Z',
    endDate:  '2026-05-22T22:00:00Z',
    type: 'public',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'A collection of 8,888 generative neon-themed NFTs on Ethereum.',
    tags: ['PFP', 'Generative'],
    featured: true,
  },
  {
    id: 'pixel-punks-reborn',
    name: 'Pixel Punks Reborn',
    image: 'https://picsum.photos/seed/pixelpunks/400/400',
    banner: 'https://picsum.photos/seed/pixelpunksBanner/800/300',
    chain: 'base',
    price: '0.005',
    currency: 'ETH',
    supply: 5000,
    mintDate: '2026-05-23T15:00:00Z',
    endDate:  '2026-05-24T15:00:00Z',
    type: 'whitelist',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Pixel art punks reborn on Base. Only 5,000 ever.',
    tags: ['Pixel', 'PFP'],
    featured: true,
  },
  {
    id: 'cosmic-apes',
    name: 'Cosmic Apes',
    image: 'https://picsum.photos/seed/cosmicapes/400/400',
    banner: 'https://picsum.photos/seed/cosmicapesBanner/800/300',
    chain: 'polygon',
    price: '25',
    currency: 'POL',
    supply: 10000,
    mintDate: '2026-05-24T20:00:00Z',
    endDate:  '2026-05-25T20:00:00Z',
    type: 'public',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Space-exploring apes on Polygon with staking rewards.',
    tags: ['PFP', 'Gaming', 'Staking'],
    featured: false,
  },
  {
    id: 'void-fragments',
    name: 'Void Fragments',
    image: 'https://picsum.photos/seed/voidfrag/400/400',
    banner: 'https://picsum.photos/seed/voidfragBanner/800/300',
    chain: 'arbitrum',
    price: 'FREE',
    currency: 'ETH',
    supply: 3333,
    mintDate: '2026-05-25T14:00:00Z',
    endDate:  '2026-05-26T14:00:00Z',
    type: 'free',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Free mint on Arbitrum. Abstract void-themed art pieces.',
    tags: ['Art', 'Abstract', 'Free'],
    featured: true,
  },
  {
    id: 'solana-spirits',
    name: 'Solana Spirits',
    image: 'https://picsum.photos/seed/solanaspirits/400/400',
    banner: 'https://picsum.photos/seed/solanaspiritsBanner/800/300',
    chain: 'solana',
    price: '0.5',
    currency: 'SOL',
    supply: 6666,
    mintDate: '2026-05-26T16:00:00Z',
    endDate:  '2026-05-27T16:00:00Z',
    type: 'public',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Ethereal spirits living on Solana. Each NFT grants DAO voting rights and staking yield.',
    tags: ['PFP', 'DAO', 'Staking'],
    featured: true,
  },
  {
    id: 'crypto-samurai',
    name: 'Crypto Samurai',
    image: 'https://picsum.photos/seed/cryptosamurai/400/400',
    banner: 'https://picsum.photos/seed/cryptosamuraiBanner/800/300',
    chain: 'ethereum',
    price: '0.15',
    currency: 'ETH',
    supply: 7777,
    mintDate: '2026-05-26T17:00:00Z',
    endDate:  '2026-05-27T17:00:00Z',
    type: 'whitelist',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Warriors of the blockchain. 7,777 unique samurai with legendary traits.',
    tags: ['PFP', 'Gaming', 'Lore'],
    featured: false,
  },
  {
    id: 'aurora-dreams',
    name: 'Aurora Dreams',
    image: 'https://picsum.photos/seed/aurora/400/400',
    banner: 'https://picsum.photos/seed/auroraBanner/800/300',
    chain: 'base',
    price: '0.003',
    currency: 'ETH',
    supply: 2000,
    mintDate: '2026-05-27T12:00:00Z',
    endDate:  '2026-05-28T12:00:00Z',
    type: 'public',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Dreamy aurora-inspired generative art on Base.',
    tags: ['Art', 'Generative'],
    featured: false,
  },
  {
    id: 'degen-toadz',
    name: 'Degen Toadz',
    image: 'https://picsum.photos/seed/degentoadz/400/400',
    banner: 'https://picsum.photos/seed/degentoadzBanner/800/300',
    chain: 'ethereum',
    price: '0.04',
    currency: 'ETH',
    supply: 6969,
    mintDate: '2026-05-28T19:00:00Z',
    endDate:  '2026-05-29T19:00:00Z',
    type: 'public',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'The degen toadz are here. 6,969 amphibians ready for the metaverse.',
    tags: ['PFP', 'Meme'],
    featured: false,
  },
  {
    id: 'stellar-knights',
    name: 'Stellar Knights',
    image: 'https://picsum.photos/seed/stellarknights/400/400',
    banner: 'https://picsum.photos/seed/stellarknightsBanner/800/300',
    chain: 'arbitrum',
    price: '0.02',
    currency: 'ETH',
    supply: 4444,
    mintDate: '2026-05-29T16:00:00Z',
    endDate:  '2026-05-30T16:00:00Z',
    type: 'whitelist',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Galactic knights on Arbitrum with on-chain RPG mechanics.',
    tags: ['Gaming', 'RPG'],
    featured: true,
  },
  {
    id: 'sol-degens',
    name: 'Sol Degens',
    image: 'https://picsum.photos/seed/soldegens/400/400',
    banner: 'https://picsum.photos/seed/soldegensanner/800/300',
    chain: 'solana',
    price: 'FREE',
    currency: 'SOL',
    supply: 10000,
    mintDate: '2026-05-30T14:00:00Z',
    endDate:  '2026-05-31T14:00:00Z',
    type: 'free',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Free mint on Solana. Bold degen characters with compressed NFT technology.',
    tags: ['PFP', 'Free', 'cNFT'],
    featured: false,
  },
  {
    id: 'glitch-world',
    name: 'Glitch World',
    image: 'https://picsum.photos/seed/glitchworld/400/400',
    banner: 'https://picsum.photos/seed/glitchworldBanner/800/300',
    chain: 'polygon',
    price: '10',
    currency: 'POL',
    supply: 9999,
    mintDate: '2026-05-30T18:00:00Z',
    endDate:  '2026-05-31T18:00:00Z',
    type: 'public',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Glitch art meets Web3. 9,999 corrupted pixels with utility.',
    tags: ['Art', 'Glitch', 'Utility'],
    featured: false,
  },
  {
    id: 'quantum-cats',
    name: 'Quantum Cats',
    image: 'https://picsum.photos/seed/quantumcats/400/400',
    banner: 'https://picsum.photos/seed/quantumcatsBanner/800/300',
    chain: 'base',
    price: 'FREE',
    currency: 'ETH',
    supply: 11111,
    mintDate: '2026-06-01T14:00:00Z',
    endDate:  '2026-06-02T14:00:00Z',
    type: 'free',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Schrödinger\'s cats enter the blockchain. Free mint, no gas wars.',
    tags: ['PFP', 'Free', 'Cats'],
    featured: true,
  },
  {
    id: 'shadow-guild',
    name: 'Shadow Guild',
    image: 'https://picsum.photos/seed/shadowguild/400/400',
    banner: 'https://picsum.photos/seed/shadowguildBanner/800/300',
    chain: 'ethereum',
    price: '0.12',
    currency: 'ETH',
    supply: 5555,
    mintDate: '2026-06-03T17:00:00Z',
    endDate:  '2026-06-04T17:00:00Z',
    type: 'whitelist',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Dark fantasy guild members with exclusive DAO access.',
    tags: ['PFP', 'DAO', 'Gaming'],
    featured: false,
  },
  {
    id: 'retro-racers',
    name: 'Retro Racers',
    image: 'https://picsum.photos/seed/retroracers/400/400',
    banner: 'https://picsum.photos/seed/retroracersBanner/800/300',
    chain: 'arbitrum',
    price: '0.01',
    currency: 'ETH',
    supply: 8000,
    mintDate: '2026-06-05T20:00:00Z',
    endDate:  '2026-06-06T20:00:00Z',
    type: 'public',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Race your NFTs in the Retro Racers on-chain game. Win ETH prizes.',
    tags: ['Gaming', 'P2E', 'Racing'],
    featured: false,
  },
  // Ended (past)
  {
    id: 'lunar-apes',
    name: 'Lunar Apes',
    image: 'https://picsum.photos/seed/lunarapes/400/400',
    banner: 'https://picsum.photos/seed/lunaarapesBanner/800/300',
    chain: 'ethereum',
    price: '0.08',
    currency: 'ETH',
    supply: 10000,
    mintDate: '2026-05-18T18:00:00Z',
    endDate:  '2026-05-19T18:00:00Z',
    type: 'public',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Moon-themed apes, sold out in under 10 minutes.',
    tags: ['PFP', 'Sold Out'],
    featured: false,
  },
  {
    id: 'digital-wolves',
    name: 'Digital Wolves',
    image: 'https://picsum.photos/seed/digitalwolves/400/400',
    banner: 'https://picsum.photos/seed/digitalwolvesBanner/800/300',
    chain: 'polygon',
    price: '15',
    currency: 'POL',
    supply: 3000,
    mintDate: '2026-05-19T16:00:00Z',
    endDate:  '2026-05-20T16:00:00Z',
    type: 'whitelist',
    website: 'https://example.com',
    twitter: 'https://twitter.com',
    discord: 'https://discord.gg',
    description: 'Pixel wolves with staking utility on Polygon.',
    tags: ['PFP', 'Pixel'],
    featured: false,
  },
]

export const CHAINS = {
  ethereum: { label: 'Ethereum', color: '#627eea', symbol: 'ETH', icon: '⟠' },
  base:     { label: 'Base',     color: '#2563eb', symbol: 'ETH', icon: '🔵' },
  polygon:  { label: 'Polygon',  color: '#8247e5', symbol: 'POL', icon: '🟣' },
  arbitrum: { label: 'Arbitrum', color: '#12aaff', symbol: 'ETH', icon: '🔷' },
  solana:   { label: 'Solana',   color: '#9945ff', symbol: 'SOL', icon: '◎'  },
}

export function getMintStatus(mint) {
  const now   = Date.now()
  const start = new Date(mint.mintDate).getTime()
  const end   = new Date(mint.endDate).getTime()
  if (now < start) return 'upcoming'
  if (now >= start && now <= end) return 'live'
  return 'ended'
}

export function getMintById(id) {
  return MINTS.find(m => m.id === id) ?? null
}
